<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Ulysses Style Sheet</string>
	<key>scopeName</key>
	<string>source.ulss</string>
	<key>fileTypes</key>
	<array>
		<string>ulss</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~U</string>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>meta.comment.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.double-slash.ulss</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>comment</key>
					<string>Multi-line comments are currently unsupported.</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>invalid.unimplemented.comment.block.ulss</string>
				</dict>
			</array>
		</dict>
		<key>selector</key>
		<dict>
			<key>begin</key>
			<string>(?=[@*:a-zA-Z\+\&gt;])</string>
			<key>end</key>
			<string>(?=(\s|[/{]))</string>
			<key>name</key>
			<string>meta.selector.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\+\&gt;]</string>
					<key>name</key>
					<string>keyword.operator.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ulysses-whitespace|ulysses-tag|ulysses-escape-character|ulysses-escape|paragraph-filename|paragraph-figure|paragraph-divider|paragraph|media-image|list-unordered|list-ordered|list-all|inline-strong|inline-raw|inline-mark|inline-link|inline-footnote|inline-emphasis|inline-delete|inline-comment|inline-code|inline-citation|inline-annotation|heading-all|heading-[1-6]|document-settings|defaults|block-raw|block-quote|block-comment|block-code|block-all|area-header|area-footnotes|area-footer)\b</string>
					<key>name</key>
					<string>entity.name.tag.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.tag.wildcard.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\@[-a-zA-Z0-9]*</string>
					<key>name</key>
					<string>entity.name.function.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:\s*\@[-a-zA-Z0-9]*</string>
					<key>name</key>
					<string>entity.other.inherited-class.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:(right-page|left-page|last|first-page|first|enumerator|anchor)</string>
					<key>name</key>
					<string>entity.other.attribute-name.pseudo-class</string>
				</dict>
			</array>
		</dict>
		<key>style-definition</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-group.begin.ulss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.property-group.end.ulss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.style-definition.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![-a-z])(?=[-a-z])</string>
					<key>end</key>
					<string>$|(?![-a-z])</string>
					<key>name</key>
					<string>meta.setting-identifier.ulss</string>
					<key>include</key>
					<string>#setting-identifier</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.ulss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(\n|;|(?=\}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.rule.ulss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.style-value.ulss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>setting-identifier</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;![-a-z])(?=[-a-z])</string>
			<key>end</key>
			<string>(?![-a-z])</string>
			<key>name</key>
			<string>meta.property-name.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(visibility|underline-color|underline|two-sided|top-spacing|text-inset|text-alignment|tab-positions|tab-alignments|style-title|strikethrough-color|strikethrough|section-break|paragraph-divider|page-width|page-orientation|page-number-style|page-number-reset|page-number-format|page-inset-top|page-inset-outer|page-inset-inner|page-inset-bottom|page-height|page-break|page-binding|orphans-and-widows|margin-top|margin-right|margin-left|margin-bottom|locale|line-spacing|line-height|keep-with-following|itemization|item-spacing|hyphenation|footnote-visibility|footnote-style|footnote-placement|footnote-enumeration|font-weight|font-style|font-slant|font-size|font-family|font-color|first-line-indent|enumeration-style|enumeration-format|divider-width|divider-spacing|divider-position|divider-length|default-tab-interval|content|column-spacing-width|column-count|character-spacing|bottom-spacing|baseline-shift|background-color|anchor-inset|anchor-alignment)\b</string>
					<key>name</key>
					<string>support.type.property-name.ulss</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>name</key>
			<string>meta.expression.ulss</string>
			<key>end</key>
			<string>($|\;|(?=//))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.ulss</string>
					<key>match</key>
					<string>[\+\-\*\/\(\)]</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#color-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbolic-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#length-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-value</string>
				</dict>
			</array>
		</dict>
		<key>array-value</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.json</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.json</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.ulss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.ulss</string>
				</dict>
			</array>
		</dict>
		<key>symbolic-value</key>
		<dict>
			<key>match</key>
			<string>(yes|visible|uppercase-roman|uppercase-alpha|true|superscript|subscript|single|right|portrait|prevented|per-section|per-page|paragraph-divider|page-number|normal|none|no|lowercase-roman|lowercase-alpha|left|landscape|justified|itemize|italic|hidden|heading(-(all|[1-6]))?|false|end-of-section|end-of-page|end-of-document|decimal|continuous|chicago-style-manual|center|bold|before|auto|after|allowed)</string>
			<key>name</key>
			<string>constant.language.ulss</string>
		</dict>
		<key>color-value</key>
		<dict>
			<key>name</key>
			<string>constant.other.color.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\#[a-f0-9A-F]{6}</string>
					<key>name</key>
					<string>constant.other.color.rgb-value.ulss</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(rgb)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.misc.ulss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.ulss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.ulss</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>constant.other.color.rgb-value.ulss</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.other.color.rgb-value.ulss</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.color.rgb-value.ulss</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(0|(?:[1-9][0-9]{0,2}))\s*(,)\s*(0|(?:[1-9][0-9]{0,2}))\s*(,)\s*(0|(?:[1-9][0-9]{0,2}))\s*</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string-value</key>
		<dict>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>name</key>
			<string>string.quoted.double.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ulss</string>
				</dict>
			</array>
		</dict>
		<key>length-value</key>
		<dict>
			<key>name</key>
			<string>meta.length-value.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(0|-?[1-9][0-9]*)(\.[0-9]+)?(pt|em|ex|en|mm|cm|in|%)\b</string>
					<key>name</key>
					<string>constant.numeric.ulss</string>
				</dict>
			</array>
		</dict>
		<key>numeric-value</key>
		<dict>
			<key>name</key>
			<string>meta.numeric-value.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(0|-?[1-9][0-9]*)(\.[0-9]+)?\b</string>
					<key>name</key>
					<string>constant.numeric.ulss</string>
				</dict>
			</array>
		</dict>
		<key>boolean-value</key>
		<dict>
			<key>name</key>
			<string>meta.boolean-value.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(yes|Yes|YES|true|True|TRUE|no|NO|No|false|FALSE|False)\b</string>
					<key>name</key>
					<string>constant.language.ulss</string>
				</dict>
			</array>
		</dict>
		<key>variable-identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.ulss</string>
					<key>match</key>
					<string>\$[a-zA-Z][a-zA-Z0-9\-]*</string>
				</dict>
			</array>
		</dict>
		<key>variable-definition</key>
		<dict>
			<key>name</key>
			<string>meta.variable-definition.ulss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-identifier</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.ulss</string>
				</dict>
				<dict>
					<key>end</key>
					<string>(\;)|(//)|$</string>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
			<key>begin</key>
			<string>(?=\$)</string>
			<key>end</key>
			<string>(\;)|(?=//)|$</string>
		</dict>
	</dict>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selector</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#style-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable-definition</string>
		</dict>
	</array>
</dict>
</plist>
